#%RAML 1.0 DataType
type: object
properties:
  firstName:
    required: true
    type: string
    description: firstName
    example:
      "Supriya"
  lastName:
    required: true
    type: string
    description: lastName
    example: "Viswanath"
  RollNumber:
    type: number
  age?: number
  class?: string
